// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_bidirectional_position_links
Rcpp::DataFrame create_bidirectional_position_links(const Rcpp::DataFrame& outliers_direct, const Rcpp::DataFrame& position_data);
RcppExport SEXP _GWESExplorer_create_bidirectional_position_links(SEXP outliers_directSEXP, SEXP position_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type position_data(position_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(create_bidirectional_position_links(outliers_direct, position_data));
    return rcpp_result_gen;
END_RCPP
}
// sort_feature_links_for_tooltips
Rcpp::DataFrame sort_feature_links_for_tooltips(const Rcpp::DataFrame& position_links);
RcppExport SEXP _GWESExplorer_sort_feature_links_for_tooltips(SEXP position_linksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type position_links(position_linksSEXP);
    rcpp_result_gen = Rcpp::wrap(sort_feature_links_for_tooltips(position_links));
    return rcpp_result_gen;
END_RCPP
}
// get_gff_name_from_attributes
Rcpp::CharacterVector get_gff_name_from_attributes(const Rcpp::CharacterVector& attributes);
RcppExport SEXP _GWESExplorer_get_gff_name_from_attributes(SEXP attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type attributes(attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_gff_name_from_attributes(attributes));
    return rcpp_result_gen;
END_RCPP
}
// find_igrs_with_outliers
Rcpp::DataFrame find_igrs_with_outliers(const Rcpp::NumericVector& gene_start_positions, const Rcpp::NumericVector& gene_end_positions, const Rcpp::List& outliers_direct, const Rcpp::NumericVector& region_ranges);
RcppExport SEXP _GWESExplorer_find_igrs_with_outliers(SEXP gene_start_positionsSEXP, SEXP gene_end_positionsSEXP, SEXP outliers_directSEXP, SEXP region_rangesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_start_positions(gene_start_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_end_positions(gene_end_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type region_ranges(region_rangesSEXP);
    rcpp_result_gen = Rcpp::wrap(find_igrs_with_outliers(gene_start_positions, gene_end_positions, outliers_direct, region_ranges));
    return rcpp_result_gen;
END_RCPP
}
// find_outlier_feature_rows
Rcpp::DataFrame find_outlier_feature_rows(const Rcpp::NumericVector& feature_start_positions, const Rcpp::NumericVector& feature_end_positions, const Rcpp::IntegerVector& outlier_positions_1, const Rcpp::IntegerVector& outlier_positions_2);
RcppExport SEXP _GWESExplorer_find_outlier_feature_rows(SEXP feature_start_positionsSEXP, SEXP feature_end_positionsSEXP, SEXP outlier_positions_1SEXP, SEXP outlier_positions_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type feature_start_positions(feature_start_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type feature_end_positions(feature_end_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type outlier_positions_1(outlier_positions_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type outlier_positions_2(outlier_positions_2SEXP);
    rcpp_result_gen = Rcpp::wrap(find_outlier_feature_rows(feature_start_positions, feature_end_positions, outlier_positions_1, outlier_positions_2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GWESExplorer_create_bidirectional_position_links", (DL_FUNC) &_GWESExplorer_create_bidirectional_position_links, 2},
    {"_GWESExplorer_sort_feature_links_for_tooltips", (DL_FUNC) &_GWESExplorer_sort_feature_links_for_tooltips, 1},
    {"_GWESExplorer_get_gff_name_from_attributes", (DL_FUNC) &_GWESExplorer_get_gff_name_from_attributes, 1},
    {"_GWESExplorer_find_igrs_with_outliers", (DL_FUNC) &_GWESExplorer_find_igrs_with_outliers, 4},
    {"_GWESExplorer_find_outlier_feature_rows", (DL_FUNC) &_GWESExplorer_find_outlier_feature_rows, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GWESExplorer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
