// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_pos_links
Rcpp::DataFrame create_pos_links(Rcpp::List outliers_direct, Rcpp::List pos_data);
RcppExport SEXP _GWESExplorer_create_pos_links(SEXP outliers_directSEXP, SEXP pos_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type pos_data(pos_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(create_pos_links(outliers_direct, pos_data));
    return rcpp_result_gen;
END_RCPP
}
// sorted_pos_links
Rcpp::DataFrame sorted_pos_links(Rcpp::List pos_links);
RcppExport SEXP _GWESExplorer_sorted_pos_links(SEXP pos_linksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pos_links(pos_linksSEXP);
    rcpp_result_gen = Rcpp::wrap(sorted_pos_links(pos_links));
    return rcpp_result_gen;
END_RCPP
}
// get_gff_name_from_attributes
Rcpp::CharacterVector get_gff_name_from_attributes(const Rcpp::CharacterVector& attributes);
RcppExport SEXP _GWESExplorer_get_gff_name_from_attributes(SEXP attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type attributes(attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_gff_name_from_attributes(attributes));
    return rcpp_result_gen;
END_RCPP
}
// find_igrs_with_outliers
Rcpp::DataFrame find_igrs_with_outliers(const Rcpp::NumericVector& gene_start_positions, const Rcpp::NumericVector& gene_end_positions, const Rcpp::List& outliers_direct, const Rcpp::NumericVector& region_ranges);
RcppExport SEXP _GWESExplorer_find_igrs_with_outliers(SEXP gene_start_positionsSEXP, SEXP gene_end_positionsSEXP, SEXP outliers_directSEXP, SEXP region_rangesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_start_positions(gene_start_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_end_positions(gene_end_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type region_ranges(region_rangesSEXP);
    rcpp_result_gen = Rcpp::wrap(find_igrs_with_outliers(gene_start_positions, gene_end_positions, outliers_direct, region_ranges));
    return rcpp_result_gen;
END_RCPP
}
// find_outlier_gene_or_igr_indices
Rcpp::DataFrame find_outlier_gene_or_igr_indices(const Rcpp::NumericVector& gene_or_igr_start_positions, const Rcpp::NumericVector& gene_or_igr_end_positions, const Rcpp::NumericVector& outlier_positions_1, const Rcpp::NumericVector& outlier_positions_2);
RcppExport SEXP _GWESExplorer_find_outlier_gene_or_igr_indices(SEXP gene_or_igr_start_positionsSEXP, SEXP gene_or_igr_end_positionsSEXP, SEXP outlier_positions_1SEXP, SEXP outlier_positions_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_or_igr_start_positions(gene_or_igr_start_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gene_or_igr_end_positions(gene_or_igr_end_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type outlier_positions_1(outlier_positions_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type outlier_positions_2(outlier_positions_2SEXP);
    rcpp_result_gen = Rcpp::wrap(find_outlier_gene_or_igr_indices(gene_or_igr_start_positions, gene_or_igr_end_positions, outlier_positions_1, outlier_positions_2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GWESExplorer_create_pos_links", (DL_FUNC) &_GWESExplorer_create_pos_links, 2},
    {"_GWESExplorer_sorted_pos_links", (DL_FUNC) &_GWESExplorer_sorted_pos_links, 1},
    {"_GWESExplorer_get_gff_name_from_attributes", (DL_FUNC) &_GWESExplorer_get_gff_name_from_attributes, 1},
    {"_GWESExplorer_find_igrs_with_outliers", (DL_FUNC) &_GWESExplorer_find_igrs_with_outliers, 4},
    {"_GWESExplorer_find_outlier_gene_or_igr_indices", (DL_FUNC) &_GWESExplorer_find_outlier_gene_or_igr_indices, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GWESExplorer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
