// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_pos_links
Rcpp::DataFrame create_pos_links(Rcpp::List outliers_direct, Rcpp::List pos_data);
RcppExport SEXP _GWESExplorer_create_pos_links(SEXP outliers_directSEXP, SEXP pos_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type pos_data(pos_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(create_pos_links(outliers_direct, pos_data));
    return rcpp_result_gen;
END_RCPP
}
// sorted_pos_links
Rcpp::DataFrame sorted_pos_links(Rcpp::List pos_links);
RcppExport SEXP _GWESExplorer_sorted_pos_links(SEXP pos_linksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pos_links(pos_linksSEXP);
    rcpp_result_gen = Rcpp::wrap(sorted_pos_links(pos_links));
    return rcpp_result_gen;
END_RCPP
}
// extract_gff_name_from_attributes
Rcpp::CharacterVector extract_gff_name_from_attributes(Rcpp::CharacterVector attributes);
RcppExport SEXP _GWESExplorer_extract_gff_name_from_attributes(SEXP attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type attributes(attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_gff_name_from_attributes(attributes));
    return rcpp_result_gen;
END_RCPP
}
// add_igrs_to_gff
Rcpp::DataFrame add_igrs_to_gff(Rcpp::List gff, Rcpp::List outliers_direct, Rcpp::NumericVector ranges);
RcppExport SEXP _GWESExplorer_add_igrs_to_gff(SEXP gffSEXP, SEXP outliers_directSEXP, SEXP rangesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type gff(gffSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type outliers_direct(outliers_directSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ranges(rangesSEXP);
    rcpp_result_gen = Rcpp::wrap(add_igrs_to_gff(gff, outliers_direct, ranges));
    return rcpp_result_gen;
END_RCPP
}
// compute_outlier_genes
Rcpp::DataFrame compute_outlier_genes(Rcpp::List gff, Rcpp::List outliers_direct);
RcppExport SEXP _GWESExplorer_compute_outlier_genes(SEXP gffSEXP, SEXP outliers_directSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type gff(gffSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type outliers_direct(outliers_directSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_outlier_genes(gff, outliers_direct));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GWESExplorer_create_pos_links", (DL_FUNC) &_GWESExplorer_create_pos_links, 2},
    {"_GWESExplorer_sorted_pos_links", (DL_FUNC) &_GWESExplorer_sorted_pos_links, 1},
    {"_GWESExplorer_extract_gff_name_from_attributes", (DL_FUNC) &_GWESExplorer_extract_gff_name_from_attributes, 1},
    {"_GWESExplorer_add_igrs_to_gff", (DL_FUNC) &_GWESExplorer_add_igrs_to_gff, 3},
    {"_GWESExplorer_compute_outlier_genes", (DL_FUNC) &_GWESExplorer_compute_outlier_genes, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GWESExplorer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
