.get_cp_color_background <- function() { .settings$circular_plot_color_background }
.get_cp_color_pos_link_connected <- function() { .settings$circular_plot_color_pos_link_connected }
.get_cp_color_pos_link_default <- function() { .settings$circular_plot_color_pos_link_default }
.get_cp_color_pos_link_inactive <- function() { .settings$circular_plot_color_pos_link_inactive }
.get_cp_color_pos_link_selected <- function() { .settings$circular_plot_color_pos_link_selected }
.get_cp_color_pos_symbol_fill <- function() { .settings$circular_plot_color_pos_symbol_fill }
.get_cp_color_pos_symbol_stroke <- function() { .settings$circular_plot_color_pos_symbol_stroke }
.get_cp_color_scheme_active <- function() { .settings$circular_plot_color_scheme_active }
.get_cp_color_scheme_default <- function() {.settings$circular_plot_color_scheme_default }
.get_cp_color_scheme_inactive <- function() { .settings$circular_plot_color_scheme_inactive }
.get_cp_color_scheme_selected <- function() { .settings$circular_plot_color_scheme_selected }
.get_cp_extent <- function() { .settings$circular_plot_extent }
.get_cp_gene_arc_angle <- function() { .settings$circular_plot_gene_circle_arc_angle }
.get_cp_groups <- function() { .settings$circular_plot_n_groups }
.get_cp_opacity_active <- function() { .settings$circular_plot_opacity_active }
.get_cp_opacity_background <- function() { .settings$circular_plot_opacity_background }
.get_cp_opacity_connected <- function() { .settings$circular_plot_opacity_connected }
.get_cp_opacity_default <- function() { .settings$circular_plot_opacity_default }
.get_cp_opacity_inactive <- function() { .settings$circular_plot_opacity_inactive }
.get_cp_opacity_region_link_active <- function() { .settings$circular_plot_opacity_region_link_active }
.get_cp_opacity_region_link_connected <- function() { .settings$circular_plot_opacity_region_link_connected }
.get_cp_opacity_region_link_default <- function() { .settings$circular_plot_opacity_region_link_default }
.get_cp_opacity_region_link_inactive <- function() { .settings$circular_plot_opacity_region_link_inactive }
.get_cp_opacity_region_link_selected <- function() { .settings$circular_plot_opacity_region_link_selected }
.get_cp_opacity_pos_link_connected <- function() { .settings$circular_plot_opacity_pos_link_connected }
.get_cp_opacity_pos_link_default <- function() { .settings$circular_plot_opacity_pos_link_default }
.get_cp_opacity_pos_link_inactive <- function() { .settings$circular_plot_opacity_pos_link_inactive }
.get_cp_opacity_pos_link_selected <- function() { .settings$circular_plot_opacity_pos_link_selected }
.get_cp_opacity_selected <- function() { .settings$circular_plot_opacity_selected }
.get_cp_padding <- function() { .settings$circular_plot_padding }
.get_cp_radius <- function() { .settings$circular_plot_radius }
.get_cp_radius_offset <- function() { .settings$circular_plot_radius_offset }
.get_cp_radius_offset_adjustment <- function() { .settings$circular_plot_radius_offset_adjustment }
.get_cp_regions <- function() { .settings$circular_plot_n_regions }
.get_cp_rotate <- function() { .settings$circular_plot_rotate }
.get_cp_size <- function() { 2.1 * .get_cp_radius() } # Add extra for plot margins.
.get_cp_tension <- function() { .settings$circular_plot_tension }
.get_cp_text_size_gene <- function(){ .settings$circular_plot_text_size_gene }
.get_cp_text_size_region <- function() { .settings$circular_plot_text_size_region }
.get_cp_text_size_tooltip <- function() { .settings$circular_plot_text_size_tooltip }
