# Default settings.
.settings$circular_plot_color_background              <- "#bfdfff"
.settings$circular_plot_color_gene_arc                <- "#3b71d9"
.settings$circular_plot_color_pos_link_connected      <- "#9b39cc"
.settings$circular_plot_color_pos_link_default        <- "#0099cc"
.settings$circular_plot_color_pos_link_inactive       <- "#9dbec9"
.settings$circular_plot_color_pos_link_selected       <- "#8800cc"
.settings$circular_plot_color_pos_symbol_fill         <- "#d3d3d3"
.settings$circular_plot_color_pos_symbol_stroke       <- "#cc3300"
.settings$circular_plot_color_region_arc              <- "#5992ff"
.settings$circular_plot_color_scheme_active           <- "teals"
.settings$circular_plot_color_scheme_default          <- "purples"
.settings$circular_plot_color_scheme_inactive         <- "greys"
.settings$circular_plot_color_scheme_selected         <- "reds"
.settings$circular_plot_extent                        <- 360
.settings$circular_plot_flip_gene_view_1              <- FALSE
.settings$circular_plot_flip_gene_view_2              <- TRUE
.settings$circular_plot_gene_arc_angle_1              <- 45
.settings$circular_plot_gene_arc_angle_2              <- 45
.settings$circular_plot_n_groups                      <- 12
.settings$circular_plot_n_regions_per_group           <- 10
.settings$circular_plot_opacity_active                <- 1
.settings$circular_plot_opacity_background            <- 1
.settings$circular_plot_opacity_connected             <- 0.5
.settings$circular_plot_opacity_default               <- 0.6
.settings$circular_plot_opacity_inactive              <- 0.2
.settings$circular_plot_opacity_region_link_active    <- 1
.settings$circular_plot_opacity_region_link_connected <- 0.5
.settings$circular_plot_opacity_region_link_default   <- 0.6
.settings$circular_plot_opacity_region_link_inactive  <- 0.2
.settings$circular_plot_opacity_region_link_selected  <- 1
.settings$circular_plot_opacity_pos_link_connected    <- 0.9
.settings$circular_plot_opacity_pos_link_default      <- 1
.settings$circular_plot_opacity_pos_link_inactive     <- 0.8
.settings$circular_plot_opacity_pos_link_selected     <- 1
.settings$circular_plot_opacity_selected              <- 1
.settings$circular_plot_padding                       <- 5
.settings$circular_plot_radius                        <- 400
.settings$circular_plot_radius_gene_view_1            <- 300
.settings$circular_plot_radius_gene_view_2            <- 250
.settings$circular_plot_rotate                        <- 0
.settings$circular_plot_rotate_gene_view_1            <- 0
.settings$circular_plot_rotate_gene_view_2            <- 0
.settings$circular_plot_tension                       <- 0.7
.settings$circular_plot_text_size_gene                <- 8
.settings$circular_plot_text_size_region              <- 12
.settings$circular_plot_text_size_tooltip             <- 10
