.circular_plot_color_background              <- function()      .settings$circular_plot_color_background
.circular_plot_color_gene_arc                <- function()      .settings$circular_plot_color_gene_arc
.circular_plot_color_pos_link_connected      <- function()      .settings$circular_plot_color_pos_link_connected
.circular_plot_color_pos_link_default        <- function()      .settings$circular_plot_color_pos_link_default
.circular_plot_color_pos_link_inactive       <- function()      .settings$circular_plot_color_pos_link_inactive
.circular_plot_color_pos_link_selected       <- function()      .settings$circular_plot_color_pos_link_selected
.circular_plot_color_pos_symbol_fill         <- function()      .settings$circular_plot_color_pos_symbol_fill
.circular_plot_color_pos_symbol_stroke       <- function()      .settings$circular_plot_color_pos_symbol_stroke
.circular_plot_color_region_arc              <- function()      .settings$circular_plot_color_region_arc
.circular_plot_color_scheme_active           <- function()      .settings$circular_plot_color_scheme_active
.circular_plot_color_scheme_default          <- function()      .settings$circular_plot_color_scheme_default
.circular_plot_color_scheme_inactive         <- function()      .settings$circular_plot_color_scheme_inactive
.circular_plot_color_scheme_selected         <- function()      .settings$circular_plot_color_scheme_selected
.circular_plot_extent                        <- function()      .settings$circular_plot_extent
.circular_plot_flip_gene_view_1              <- function()      .settings$circular_plot_flip_gene_view_1
.circular_plot_flip_gene_view_2              <- function()      .settings$circular_plot_flip_gene_view_2
.circular_plot_gene_arc_angle_1              <- function()      .settings$circular_plot_gene_arc_angle_1
.circular_plot_gene_arc_angle_2              <- function()      .settings$circular_plot_gene_arc_angle_2
.circular_plot_groups                        <- function()      .settings$circular_plot_n_groups
.circular_plot_opacity_active                <- function()      .settings$circular_plot_opacity_active
.circular_plot_opacity_background            <- function()      .settings$circular_plot_opacity_background
.circular_plot_opacity_connected             <- function()      .settings$circular_plot_opacity_connected
.circular_plot_opacity_default               <- function()      .settings$circular_plot_opacity_default
.circular_plot_opacity_inactive              <- function()      .settings$circular_plot_opacity_inactive
.circular_plot_opacity_region_link_active    <- function()      .settings$circular_plot_opacity_region_link_active
.circular_plot_opacity_region_link_connected <- function()      .settings$circular_plot_opacity_region_link_connected
.circular_plot_opacity_region_link_default   <- function()      .settings$circular_plot_opacity_region_link_default
.circular_plot_opacity_region_link_inactive  <- function()      .settings$circular_plot_opacity_region_link_inactive
.circular_plot_opacity_region_link_selected  <- function()      .settings$circular_plot_opacity_region_link_selected
.circular_plot_opacity_pos_link_connected    <- function()      .settings$circular_plot_opacity_pos_link_connected
.circular_plot_opacity_pos_link_default      <- function()      .settings$circular_plot_opacity_pos_link_default
.circular_plot_opacity_pos_link_inactive     <- function()      .settings$circular_plot_opacity_pos_link_inactive
.circular_plot_opacity_pos_link_selected     <- function()      .settings$circular_plot_opacity_pos_link_selected
.circular_plot_opacity_selected              <- function()      .settings$circular_plot_opacity_selected
.circular_plot_padding                       <- function()      .settings$circular_plot_padding
.circular_plot_radius                        <- function()      .settings$circular_plot_radius
.circular_plot_radius_gene_view_1            <- function()      .settings$circular_plot_radius_gene_view_1
.circular_plot_radius_gene_view_2            <- function()      .settings$circular_plot_radius_gene_view_2
.circular_plot_regions_per_group             <- function()      .settings$circular_plot_n_regions_per_group
.circular_plot_regions                       <- function()      .circular_plot_groups() *
                                                                .circular_plot_regions_per_group()
.circular_plot_rotate                        <- function()      .settings$circular_plot_rotate
.circular_plot_rotate_gene_view_1            <- function()      .settings$circular_plot_rotate_gene_view_1
.circular_plot_rotate_gene_view_2            <- function()      .settings$circular_plot_rotate_gene_view_2
                                                                # Add extra for plot margins
.circular_plot_size                          <- function()      2.1 * .circular_plot_radius()
.circular_plot_tension                       <- function()      .settings$circular_plot_tension
.circular_plot_text_size_gene                <- function()      .settings$circular_plot_text_size_gene
.circular_plot_text_size_region              <- function()      .settings$circular_plot_text_size_region
.circular_plot_text_size_tooltip             <- function()      .settings$circular_plot_text_size_tooltip
