.about_panel <- function() {
    shiny::tabPanel(title = "About",
        shiny::h2("GWESalyzer - a genome-wide epistasis analyzer."),
        shiny::p("GWESalyzer is an interactive visualization tool designed to be used in conjunction with ",
        shiny::HTML('<a href="https://github.com/santeripuranen/SpydrPick" target="_blank">SpydrPick</a>.'),
        "GWESalyzer relies heavily on the Shiny and Vega libraries to deploy it as a web application with multiple plot types ",
        "to visualize the genomic data. GWESalyzer operates on the outliers file generated by SpydrPick ",
        "to produce a GWES Manhattan plot. Two additional plots can be generated, namely a phylogenetic tree ",
        "plot by providing either a Newick or a Nexus file in addition to a FASTA and a loci file, ",
        "and a highly interactive circular chromosome plot by providing a GFF3 file."),
        style = "font-size: 16px; word-wrap: break-word; width: 800px")
}
