.about_panel <- function() {
    shiny::tabPanel(title = "About",
        shiny::h2("GWES-Explorer - a genome-wide epistasis analyzer."),
        shiny::p("GWES-Explorer is an interactive visualization tool designed to be used in conjunction with ",
            shiny::HTML('<a href="https://github.com/santeripuranen/SpydrPick" target="_blank">SpydrPick</a>.'),
            "GWES-Explorer relies heavily on the Shiny and Vega libraries to deploy it as a web application with multiple plot types ",
            "to visualize the genomic data. GWES-Explorer operates on the outliers file generated by SpydrPick ",
            "to produce a GWES Manhattan plot. Two additional plots can be generated, namely a phylogenetic tree ",
            "plot by providing either a Newick or a Nexus file in addition to a FASTA and a loci file, ",
            "and a highly interactive circular chromosome plot by providing a GFF3 file.",
            shiny::br(),
            shiny::br(),
            shiny::HTML('GitHub: <a href="https://github.com/jurikuronen/GWES-Explorer" target="_blank">https://github.com/jurikuronen/GWES-Explorer</a>')
        ),
        style = "font-size: 16px; word-wrap: break-word; width: 800px")
}
