.tree_plot_panel <- function() {
    shiny::tabPanel("Tree-MSA",
        shiny::br(),
        .div_inline_block(3, "Modify figure:"),
        .div_inline_block(4, .prettySwitch("show_tree_plot_fig_size", "Figure size")),
        .div_inline_block(4, .prettySwitch("show_tree_plot_label_prop", "Column labels")),
        .div_inline_block(4, .prettySwitch("show_tree_plot_legend_prop", "Legend")),
        shiny::conditionalPanel(
            condition = "input.show_tree_plot_fig_size",
            .div_inline_block(6, shiny::sliderInput("tree_plot_width", "Figure width (cm):",
                                                    min = 10,
                                                    max = 50,
                                                    value = 20)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_plot_height", "Figure height (cm):",
                                                    min = 10,
                                                    max = 50,
                                                    value = 20)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_plot_bottom_margin_multiplier",
                                                    "Figure bottom margin multiplier:",
                                                    min = 1,
                                                    max = 20,
                                                    value = .settings$tree_plot_bottom_margin_multiplier))
        ),
        shiny::conditionalPanel(
            condition = "input.show_tree_plot_label_prop",
            .div_inline_block(6, shiny::sliderInput("tree_heatmap_column_label_angle", "Column label angle:",
                                                    min = 0,
                                                    max = 90,
                                                    value = .settings$tree_heatmap_column_label_angle)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_heatmap_column_label_font_size",
                                                    "Column label font size:",
                                                    min = 2,
                                                    max = 30,
                                                    value = .settings$tree_heatmap_column_label_font_size)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_heatmap_column_label_offset_x", "Column label offset X:",
                                                    min = 0,
                                                    max = 0.2,
                                                    value = .settings$tree_heatmap_column_label_offset_x)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_heatmap_column_label_offset_y", "Column label offset Y:",
                                                    min = 0,
                                                    max = 200,
                                                    value = .settings$tree_heatmap_column_label_offset_y))
        ),
        shiny::conditionalPanel(
            condition = "input.show_tree_plot_legend_prop",
            .div_inline_block(6, shiny::sliderInput("tree_legend_text_size", "Legend font size:",
                                                    min = 8,
                                                    max = 30,
                                                    value = .settings$tree_legend_text_size)),
            .div_inline_br_block(0.5),
            .div_inline_block(6, shiny::sliderInput("tree_legend_key_size", "Legend key size:",
                                                    min = 0.5,
                                                    max = 3,
                                                    value = .settings$tree_legend_key_size))
        ),
        shiny::br(), shiny::br(),
        shiny::uiOutput("tree_plot_ui_output"),
        shiny::br(),
        # Controls for downloading the plot.
        .plot_download_controls(
            prefix = "phylogenetic_tree_plot",
            width = 15,
            height = 15
        )
    )
}
